samples: config/samples.tsv
outdir: /mnt/hgfs/VMshared/victor
warpper_mirror: https://jihulab.com/NshimaBio/sws/-/raw/v3.3.6/ 

mNGS_idx: /mnt/hgfs/VMshared/victor
reference: /mnt/hgfs/VMshared/victor/maf/maf.fna

fastqs: /mnt/hgfs/VMshared/victor/fastq
platform: ILLUMINA
is_single_end: false
duplicates: remove
